services:
  web:
    build: .
    container_name: panel-admin
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "IP=$(hostname -i) && curl -fsS http://$IP:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 25s
