version: "3.9"

services:
  web:
    build: .
    container_name: panel-admin
    env_file: .env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:3000/" ]
      interval: 10s
      timeout: 3s
      retries: 5
