-- Crea BD
IF DB_ID('BD_ARASAC') IS NULL
BEGIN
  CREATE DATABASE BD_ARASAC;
END
GO

USE BD_ARASAC;
GO

-- Funciones "stub" para tus SELECT (ajústalas si tienes el código real)
IF OBJECT_ID('dbo.F_DES_FAMILIA') IS NOT NULL DROP FUNCTION dbo.F_DES_FAMILIA;
GO
CREATE FUNCTION dbo.F_DES_FAMILIA(@cod INT, @modo INT)
RETURNS NVARCHAR(200) AS
BEGIN
  RETURN CONCAT('FAMILIA-', @cod);
END
GO

IF OBJECT_ID('dbo.F_DES_CLASE') IS NOT NULL DROP FUNCTION dbo.F_DES_CLASE;
GO
CREATE FUNCTION dbo.F_DES_CLASE(@cod_fam INT, @cod_clase INT, @modo INT)
RETURNS NVARCHAR(200) AS
BEGIN
  RETURN CONCAT('CLASE-', @cod_fam, '-', @cod_clase);
END
GO

IF OBJECT_ID('dbo.F_DES_SUBCLASE') IS NOT NULL DROP FUNCTION dbo.F_DES_SUBCLASE;
GO
CREATE FUNCTION dbo.F_DES_SUBCLASE(@cod_fam INT, @cod_clase INT, @cod_sub INT, @modo INT)
RETURNS NVARCHAR(200) AS
BEGIN
  RETURN CONCAT('SUB-', @cod_fam, '-', @cod_clase, '-', @cod_sub);
END
GO

-- Tabla USUARIO (compatible con lo que ya consultas)
IF OBJECT_ID('dbo.USUARIO') IS NULL
BEGIN
  CREATE TABLE dbo.USUARIO (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(200) NULL,
    COD_USUARIO NVARCHAR(50) NOT NULL UNIQUE,
    email NVARCHAR(200) NULL,
    password NVARCHAR(255) NULL,
    rol_id INT NULL,
    remember_token NVARCHAR(255) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL
  );
END
GO

-- Tabla ARTICULO (mínima para tu SELECT)
IF OBJECT_ID('dbo.ARTICULO') IS NULL
BEGIN
  CREATE TABLE dbo.ARTICULO (
    COD_FAMILIA INT NOT NULL,
    COD_CLASE INT NOT NULL,
    COD_SUBCLASE INT NOT NULL,
    COD_ITEM_ARTICULO INT NOT NULL,
    COD_STANDARD NVARCHAR(50) NULL,
    DESCRIPCION_ARTICULO NVARCHAR(500) NULL
  );
END
GO

-- Data de ejemplo
TRUNCATE TABLE dbo.USUARIO;
INSERT INTO dbo.USUARIO (name, COD_USUARIO, email, password, rol_id)
VALUES
('Martin Balbin','MBALBIN','martinbalbin@gmail.com',
'$2y$10$yecW43ziOJPcrr70JAXzMuvb7jZiKRXUZ/dpzycBGVX6MR86FGbh2',1),
('Fabian Chavez','VTAENR2','fchavez@cassado.com.pe',
'$2y$10$no2RD0Ya/ZRXY0KZ3sr2qeYhbLZPx/BRvvfEJxs4aF81lVC8tJi3K',2);

TRUNCATE TABLE dbo.ARTICULO;
INSERT INTO dbo.ARTICULO (COD_FAMILIA,COD_CLASE,COD_SUBCLASE,COD_ITEM_ARTICULO,COD_STANDARD,DESCRIPCION_ARTICULO)
VALUES
(1,10,100,1000,'STD-001','Articulo demo 1'),
(1,20,200,2000,'STD-002','Articulo demo 2');
GO
