-- scripts/dev-bootstrap.sql
IF DB_ID('BD_ARASAC') IS NULL
BEGIN
  CREATE DATABASE BD_ARASAC;
END
GO

USE BD_ARASAC;
GO

-- ============================
-- TABLA USUARIO (estructura mínima + columnas reales clave)
-- ============================
IF OBJECT_ID('dbo.USUARIO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.USUARIO (
    COD_USUARIO                 VARCHAR(15)  NOT NULL,
    CLAVE_USUARIO               VARCHAR(15)  NULL,  -- legado (no lo tocamos)
    REQUIERE_TOKEN              VARCHAR(1)   NULL,
    APELLIDO_PATERNO            VARCHAR(60)  NULL,
    APELLIDO_MATERNO            VARCHAR(60)  NULL,
    PRIMER_NOMBRE               VARCHAR(60)  NULL,
    SEGUNDO_NOMBRE              VARCHAR(60)  NULL,
    NUMERO_DOCUMENTO_IDENTIDAD  VARCHAR(20)  NULL,
    NUMERO_LICENCIA             VARCHAR(20)  NULL,
    NUMERO_TELEFONO             VARCHAR(30)  NULL,
    CORREO_ELECTRONICO          VARCHAR(60)  NULL,
    COD_USUARIO_SUPERVISOR      VARCHAR(15)  NULL,
    COD_COMPANIA_INI            INT          NULL,
    COD_SUCURSAL_INI            INT          NULL,
    COD_ALMACEN_INI             INT          NULL,
    COD_TERMINAL_INI            INT          NULL,
    ALIAS1                      VARCHAR(30)  NULL,
    ALIAS2                      VARCHAR(30)  NULL,
    ALIAS3                      VARCHAR(30)  NULL,
    NOT_MEMO                    TEXT         NULL,
    COD_ESTADO_REGISTRO         INT          NOT NULL DEFAULT(1),
    COD_USUARIO_CREADOR         VARCHAR(15)  NOT NULL DEFAULT('SYSTEM'),
    FEC_CREACION                DATETIME     NOT NULL DEFAULT(GETDATE()),
    COD_USUARIO_UPDATE          VARCHAR(15)  NOT NULL DEFAULT('SYSTEM'),
    FEC_UPDATE                  DATETIME     NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT PK_USUARIO PRIMARY KEY (COD_USUARIO)
  );
END
GO

-- columnas nuevas para auth moderna
IF COL_LENGTH('dbo.USUARIO', 'PASSWORD_HASH') IS NULL
  ALTER TABLE dbo.USUARIO ADD PASSWORD_HASH VARCHAR(72) NULL;
IF COL_LENGTH('dbo.USUARIO', 'NEEDS_PASSWORD_MIG') IS NULL
  ALTER TABLE dbo.USUARIO ADD NEEDS_PASSWORD_MIG BIT NOT NULL
    CONSTRAINT DF_USUARIO_NEEDS_PASSWORD_MIG DEFAULT(1);
IF COL_LENGTH('dbo.USUARIO', 'FIRST_LOGIN') IS NULL
  ALTER TABLE dbo.USUARIO ADD FIRST_LOGIN BIT NOT NULL
    CONSTRAINT DF_USUARIO_FIRST_LOGIN DEFAULT(1);
IF COL_LENGTH('dbo.USUARIO', 'PASSWORD_SET_AT') IS NULL
  ALTER TABLE dbo.USUARIO ADD PASSWORD_SET_AT DATETIME NULL;
IF COL_LENGTH('dbo.USUARIO', 'LAST_LOGIN_AT') IS NULL
  ALTER TABLE dbo.USUARIO ADD LAST_LOGIN_AT DATETIME NULL;
GO

-- Seed usuarios de ejemplo (ajusta a tus testers)
IF NOT EXISTS (SELECT 1 FROM dbo.USUARIO WHERE COD_USUARIO='MBALBIN')
INSERT INTO dbo.USUARIO (COD_USUARIO, PRIMER_NOMBRE, APELLIDO_PATERNO, CORREO_ELECTRONICO)
VALUES ('MBALBIN', 'Martin', 'Balbin', 'martinbalbin@gmail.com');

IF NOT EXISTS (SELECT 1 FROM dbo.USUARIO WHERE COD_USUARIO='VTAENR2')
INSERT INTO dbo.USUARIO (COD_USUARIO, PRIMER_NOMBRE, APELLIDO_PATERNO, CORREO_ELECTRONICO)
VALUES ('VTAENR2', 'Fabian', 'Chavez', 'fchavez@cassado.com.pe');

-- ============================
-- TABLA ARTICULO (campos usados por tu query)
-- ============================
IF OBJECT_ID('dbo.ARTICULO', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ARTICULO(
    COD_ITEM_ARTICULO      NUMERIC(8,0) NOT NULL,
    COD_FAMILIA            INT          NOT NULL,
    COD_CLASE              INT          NOT NULL,
    COD_SUBCLASE           INT          NOT NULL,
    DESCRIPCION_ARTICULO   VARCHAR(250) NOT NULL,
    COD_PARTIDA_ARANCELARIA NUMERIC(10,0) NULL,
    COD_STANDARD           VARCHAR(30)  NULL,
    COD_ESTADO_REGISTRO    INT NOT NULL DEFAULT(1),
    FEC_CREACION           DATETIME NOT NULL DEFAULT(GETDATE()),
    FEC_UPDATE             DATETIME NOT NULL DEFAULT(GETDATE()),
    CONSTRAINT PK_ARTICULO PRIMARY KEY (COD_ITEM_ARTICULO, COD_FAMILIA, COD_CLASE, COD_SUBCLASE)
  );
END
GO

-- Funciones dummy para que tu SELECT no falle en dev
IF OBJECT_ID('dbo.F_DES_FAMILIA') IS NULL
  EXEC('CREATE FUNCTION dbo.F_DES_FAMILIA (@COD_FAMILIA INT, @TIPO INT) RETURNS VARCHAR(100) AS BEGIN RETURN (SELECT CASE WHEN @COD_FAMILIA=1 THEN ''MERCADERIAS'' ELSE ''OTRAS'' END) END');
IF OBJECT_ID('dbo.F_DES_CLASE') IS NULL
  EXEC('CREATE FUNCTION dbo.F_DES_CLASE (@COD_FAMILIA INT,@COD_CLASE INT,@TIPO INT) RETURNS VARCHAR(100) AS BEGIN RETURN ''VARIOS'' END');
IF OBJECT_ID('dbo.F_DES_SUBCLASE') IS NULL
  EXEC('CREATE FUNCTION dbo.F_DES_SUBCLASE (@COD_FAMILIA INT,@COD_CLASE INT,@COD_SUBCLASE INT,@TIPO INT) RETURNS VARCHAR(100) AS BEGIN RETURN CASE WHEN @COD_SUBCLASE=2 THEN ''ACCESORIO'' ELSE ''VARIOS'' END END');
GO

-- Seed ARTICULO (subset de tu listado)
IF NOT EXISTS (SELECT 1 FROM dbo.ARTICULO WHERE COD_ITEM_ARTICULO=1 AND COD_FAMILIA=1 AND COD_CLASE=1 AND COD_SUBCLASE=1)
INSERT INTO dbo.ARTICULO (COD_ITEM_ARTICULO, COD_FAMILIA, COD_CLASE, COD_SUBCLASE, DESCRIPCION_ARTICULO, COD_STANDARD)
VALUES (1, 1, 1, 1, 'ARTICULO VARIOS', 'VARIOS');

IF NOT EXISTS (SELECT 1 FROM dbo.ARTICULO WHERE COD_ITEM_ARTICULO=1723 AND COD_FAMILIA=1 AND COD_CLASE=1 AND COD_SUBCLASE=2)
INSERT INTO dbo.ARTICULO (COD_ITEM_ARTICULO, COD_FAMILIA, COD_CLASE, COD_SUBCLASE, DESCRIPCION_ARTICULO, COD_STANDARD)
VALUES (1723, 1, 1, 2, 'ACOPLE DE RAD ACC RIO G4FA ACKOR', '25329-1J100-AC');

IF NOT EXISTS (SELECT 1 FROM dbo.ARTICULO WHERE COD_ITEM_ARTICULO=1939 AND COD_FAMILIA=1 AND COD_CLASE=1 AND COD_SUBCLASE=2)
INSERT INTO dbo.ARTICULO (COD_ITEM_ARTICULO, COD_FAMILIA, COD_CLASE, COD_SUBCLASE, DESCRIPCION_ARTICULO, COD_STANDARD)
VALUES (1939, 1, 1, 2, 'FUNDA DELT DONGFENG 1020 1.0/1.3', '2803011-04 AT');

IF NOT EXISTS (SELECT 1 FROM dbo.ARTICULO WHERE COD_ITEM_ARTICULO=3011 AND COD_FAMILIA=1 AND COD_CLASE=1 AND COD_SUBCLASE=2)
INSERT INTO dbo.ARTICULO (COD_ITEM_ARTICULO, COD_FAMILIA, COD_CLASE, COD_SUBCLASE, DESCRIPCION_ARTICULO, COD_STANDARD)
VALUES (3011, 1, 1, 2, 'ACOPLE DE TIMON ACC RIO MOBIS', '56315-2K000');

-- ... agrega más si deseas; con esto ya responde el endpoint
GO
