-- scripts/migration-add-auth-columns.sql
USE BD_ARASAC;
GO

IF COL_LENGTH('dbo.USUARIO', 'PASSWORD_HASH') IS NULL
  ALTER TABLE dbo.USUARIO ADD PASSWORD_HASH VARCHAR(72) NULL;
IF COL_LENGTH('dbo.USUARIO', 'NEEDS_PASSWORD_MIG') IS NULL
  ALTER TABLE dbo.USUARIO ADD NEEDS_PASSWORD_MIG BIT NOT NULL
    CONSTRAINT DF_USUARIO_NEEDS_PASSWORD_MIG DEFAULT(1);
IF COL_LENGTH('dbo.USUARIO', 'FIRST_LOGIN') IS NULL
  ALTER TABLE dbo.USUARIO ADD FIRST_LOGIN BIT NOT NULL
    CONSTRAINT DF_USUARIO_FIRST_LOGIN DEFAULT(1);
IF COL_LENGTH('dbo.USUARIO', 'PASSWORD_SET_AT') IS NULL
  ALTER TABLE dbo.USUARIO ADD PASSWORD_SET_AT DATETIME NULL;
IF COL_LENGTH('dbo.USUARIO', 'LAST_LOGIN_AT') IS NULL
  ALTER TABLE dbo.USUARIO ADD LAST_LOGIN_AT DATETIME NULL;
GO

-- Opcional: índices que ayudan a login
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_USUARIO_PASSWORD_HASH' AND object_id = OBJECT_ID('dbo.USUARIO'))
  CREATE NONCLUSTERED INDEX IX_USUARIO_PASSWORD_HASH ON dbo.USUARIO (PASSWORD_HASH);
GO
